name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bats
        run: |
          git clone --branch v1.5.0 https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local

      - name: Run Bats tests
        run: bats tests/analyze-code.bats